---
setup_cadvisor_create_folder: true
setup_cadvisor_compose_folder_path: '/opt/docker/cadvisor'
setup_cadvisor_folder_owner: 'root'
setup_cadvisor_folder_group: 'root'

setup_cadvisor_project_name: 'cadvisor'
setup_cadvisor_image: 'gcr.io/cadvisor/cadvisor'
setup_cadvisor_image_tag: 'latest'

setup_cadvisor_port: 9200
...
